"""DO NOT EDIT.

This file was autogenerated. Do not edit it by hand,
since your modifications would be overwritten.
"""

from synalinks.src.knowledge_bases import deserialize as deserialize
from synalinks.src.knowledge_bases import get as get
from synalinks.src.knowledge_bases import serialize as serialize
