# DO NOT EDIT. Generated by api_gen.sh
from synalinks.api import backend
from synalinks.api import callbacks
from synalinks.api import config
from synalinks.api import datasets
from synalinks.api import embedding_models
from synalinks.api import hooks
from synalinks.api import initializers
from synalinks.api import knowledge_bases
from synalinks.api import language_models
from synalinks.api import metrics
from synalinks.api import modules
from synalinks.api import ops
from synalinks.api import optimizers
from synalinks.api import programs
from synalinks.api import rewards
from synalinks.api import sandboxes
from synalinks.api import saving
from synalinks.api import tree
from synalinks.api import tuners
from synalinks.api import utils
from synalinks.api import DataModel
from synalinks.api import name_scope
from synalinks.api import clear_session
from synalinks.api import JsonDataModel
from synalinks.api import StatelessScope
from synalinks.api import SymbolicDataModel
from synalinks.api import SymbolicScope
from synalinks.api import api_base
from synalinks.api import default_embedding_model
from synalinks.api import default_knowledge_base
from synalinks.api import default_language_model
from synalinks.api import enable_logging
from synalinks.api import enable_observability
from synalinks.api import get_seed
from synalinks.api import is_observability_enabled
from synalinks.api import set_api_base
from synalinks.api import set_default_embedding_model
from synalinks.api import set_default_knowledge_base
from synalinks.api import set_default_language_model
from synalinks.api import set_seed
from synalinks.api import synalinks_home
from synalinks.api import EmbeddingRequest
from synalinks.api import Embeddings
from synalinks.api import GenericIO
from synalinks.api import GenericInputs
from synalinks.api import GenericOutputs
from synalinks.api import GenericResult
from synalinks.api import Instructions
from synalinks.api import Prediction
from synalinks.api import Stamp
from synalinks.api import Trainable
from synalinks.api import is_embedded
from synalinks.api import is_embedding
from synalinks.api import is_embeddings
from synalinks.api import is_instructions
from synalinks.api import is_prediction
from synalinks.api import is_stamped
from synalinks.api import is_trainable
from synalinks.api import ChatCompletionChoice
from synalinks.api import ChatCompletionCompletionTokensDetails
from synalinks.api import ChatCompletionFunctionCall
from synalinks.api import ChatCompletionJsonSchema
from synalinks.api import ChatCompletionMessage
from synalinks.api import ChatCompletionPromptTokensDetails
from synalinks.api import ChatCompletionRequest
from synalinks.api import ChatCompletionResponse
from synalinks.api import ChatCompletionResponseFormat
from synalinks.api import ChatCompletionTool
from synalinks.api import ChatCompletionToolCall
from synalinks.api import ChatCompletionToolFunction
from synalinks.api import ChatCompletionUsage
from synalinks.api import from_chat_completion_message
from synalinks.api import from_chat_completion_messages
from synalinks.api import to_chat_completion_message
from synalinks.api import to_chat_completion_messages
from synalinks.api import to_chat_completion_request
from synalinks.api import ChatMessage
from synalinks.api import ChatMessages
from synalinks.api import ChatRole
from synalinks.api import ToolCall
from synalinks.api import ToolCalling
from synalinks.api import ToolCallFunction
from synalinks.api import is_chat_message
from synalinks.api import is_chat_messages
from synalinks.api import is_strictly_chat_message
from synalinks.api import is_strictly_chat_messages
from synalinks.api import is_tool_call
from synalinks.api import EmbeddedEntity
from synalinks.api import Entities
from synalinks.api import Entity
from synalinks.api import KnowledgeGraph
from synalinks.api import KnowledgeGraphs
from synalinks.api import Relation
from synalinks.api import Relations
from synalinks.api import is_embedded_entity
from synalinks.api import is_entities
from synalinks.api import is_entity
from synalinks.api import is_knowledge_graph
from synalinks.api import is_knowledge_graphs
from synalinks.api import is_relation
from synalinks.api import is_relations
from synalinks.api import Audio
from synalinks.api import Image
from synalinks.api import Score
from synalinks.api import CSVDataset
from synalinks.api import Dataset
from synalinks.api import HuggingFaceDataset
from synalinks.api import ImageFolderDataset
from synalinks.api import JSONDataset
from synalinks.api import JSONLDataset
from synalinks.api import MarkdownDataset
from synalinks.api import MarkdownDocument
from synalinks.api import MarkdownSection
from synalinks.api import parse_markdown_sections
from synalinks.api import ParquetDataset
from synalinks.api import TextDataset
from synalinks.api import TextDocument
from synalinks.api import Initializer
from synalinks.api import KnowledgeBase
from synalinks.api import GapK
from synalinks.api import PassAtK
from synalinks.api import PassHatK
from synalinks.api import BatchMetric
from synalinks.api import EmbeddingModelOperationalMetric
from synalinks.api import EmbeddingModelOptimizersOperationalMetric
from synalinks.api import EmbeddingModelRewardsOperationalMetric
from synalinks.api import LMOperationalMetric
from synalinks.api import LMOptimizersOperationalMetric
from synalinks.api import LMRewardsOperationalMetric
from synalinks.api import Metric
from synalinks.api import ProgramOperationalMetric
from synalinks.api import CypherAgent
from synalinks.api import DeepAgent
from synalinks.api import FunctionCallingAgent
from synalinks.api import RLM
from synalinks.api import RecursiveLanguageModelAgent
from synalinks.api import SQLAgent
from synalinks.api import VectorRAGAgent
from synalinks.api import Action
from synalinks.api import Branch
from synalinks.api import Decision
from synalinks.api import Generator
from synalinks.api import default_prompt_template
from synalinks.api import Identity
from synalinks.api import AudioInput
from synalinks.api import ImageInput
from synalinks.api import Input
from synalinks.api import Lambda
from synalinks.api import MultiDecision
from synalinks.api import Not
from synalinks.api import OAuthLanguageModel
from synalinks.api import Tool
from synalinks.api import EmbeddingModel
from synalinks.api import EmbedKnowledge
from synalinks.api import RetrieveKnowledge
from synalinks.api import StampKnowledge
from synalinks.api import Text2Cypher
from synalinks.api import Text2SQL
from synalinks.api import UpdateKnowledge
from synalinks.api import LanguageModel
from synalinks.api import InMask
from synalinks.api import OutMask
from synalinks.api import Concat
from synalinks.api import Concatenate
from synalinks.api import And
from synalinks.api import Or
from synalinks.api import Xor
from synalinks.api import Module
from synalinks.api import RRFReranker
from synalinks.api import EntityFullTextSearch
from synalinks.api import EntityHybridFTSSearch
from synalinks.api import EntityHybridRegexSearch
from synalinks.api import EntityRegexSearch
from synalinks.api import EntitySimilaritySearch
from synalinks.api import FullTextSearch
from synalinks.api import HybridFTSSearch
from synalinks.api import HybridRegexSearch
from synalinks.api import PathFullTextSearch
from synalinks.api import PathHybridFTSSearch
from synalinks.api import PathHybridRegexSearch
from synalinks.api import PathRegexSearch
from synalinks.api import PathSimilaritySearch
from synalinks.api import RegexSearch
from synalinks.api import RelationFullTextSearch
from synalinks.api import RelationHybridFTSSearch
from synalinks.api import RelationHybridRegexSearch
from synalinks.api import RelationRegexSearch
from synalinks.api import RelationSimilaritySearch
from synalinks.api import SimilaritySearch
from synalinks.api import PythonSynthesis
from synalinks.api import ChainOfThought
from synalinks.api import SelfCritique
from synalinks.api import Function
from synalinks.api import Operation
from synalinks.api import OMEGA
from synalinks.api import Program
from synalinks.api import Sequential
from synalinks.api import BatchReward
from synalinks.api import CosineSimilarity
from synalinks.api import ExactMatch
from synalinks.api import LMAsJudge
from synalinks.api import Reward
from synalinks.api import ProgramAsJudge
from synalinks.api import MirageSandbox
from synalinks.api import ExecutionResult
from synalinks.api import Sandbox
from synalinks.api import register_synalinks_serializable
from synalinks.api import disable_keras_backend
from synalinks.api import MultiServerMCPClient
from synalinks.api import version
from synalinks.api import __version__
# END DO NOT EDIT.

import os  # isort: skip

# Add everything in /api/ to the module search path.
__path__.append(os.path.join(os.path.dirname(__file__), "api"))  # noqa: F405

# Don't pollute namespace.
del os


# Never autocomplete `.src` or `.api` on an imported synalinks object.
def __dir__():
    keys = dict.fromkeys((globals().keys()))
    keys.pop("src")
    keys.pop("api")
    return list(keys)


# Don't import `.src`, or `.api` during `from synalinks import *`.
__all__ = [
    name
    for name in globals().keys()
    if not (name.startswith("_") or name in ("src", "api"))
]

if backend.backend() == "pydantic":
    from synalinks.src.backend import Field
